### ISSUE TITLE
Pretrained weights/models are missing

### ISSUE THREAD

**Issue by georgmartius** [SymposiumOrganization/NeuralSymbolicRegressionThatScales#1]
I cannot find the models. Are they supposed to be in this repo?

**Comment by TommasoBendinelli** [comment]
Hi, we are finishing cleaning and setting up the repo. By the end of next week, we will place the link to model weights in the README.md file.
Best,
Tommaso

**Comment by georgmartius** [comment]
Thanks a lot! I am looking forward and I am eager to try it out ;-)
