### ISSUE TITLE
error when try to  add more variables

### ISSUE THREAD

**Issue by chenyuxin1999** [SymposiumOrganization/NeuralSymbolicRegressionThatScales#10]
Thanks for making it public and really love your paper. 

At first I generate data and train the model as default settings, everything goes well. However, when I try to add two more variables in this model, some error occur. What I did is adding x_4 and x_5 in the dataset_configuration.json; regenerate training and validaion data and change the train_path as well as val_path in condig.yaml. Could you please tell me if there is some operations I missed to solve the problem. It is really important because I do want to reproduce it as one of the baseline. Thanks a lot
![截屏2022-05-30 23 44 36](https://user-images.githubusercontent.com/68749964/171025948-7c42a226-9ff9-466f-bdba-142322245611.png)

**Comment by lucabig** [comment]
Hello,

have you changed the dim_input variable in the config file?

**Comment by chenyuxin1999** [comment]
Ah that's the problem! Thanks for your help.
