### ISSUE TITLE
Inquiry on .h5 files

### ISSUE THREAD

**Issue by kpark53** [SymposiumOrganization/NeuralSymbolicRegressionThatScales#15]
Hi Tommaso,

  Thanks for the quick reply on my previous questions. I really appreciate it. I have a quick question on data generation part. Train data generator basically makes .h5 files along with metadata.h5   
  
  I tried to open it with h5 python package to see how the data really looks like but I failed in somewhat reason.(it just give me void). The reason I was trying to see the actual format of data is to use my own customized train data for my research.
  
  My question here is, - 
   Is there any specific reason why you used .h5 format in your data generation process?(I guess size issue) Also, is it possible to use other format files for training? Please kindly advise.

Thanks
Keun

**Comment by TommasoBendinelli** [comment]
Hi kpark53, I suggest you use the function load_eq (utils.py:59) to inspect the h5 files. Please note that each h5 file contains multiple equations, so load_eq is the best way to retrieve a single equation given its index. We chose this approach to get good I/O performance, while avoiding the issue of creating too many files which can be problematic if you have more than 1 million equations. (i.e. if you stored one equation in each file, you would end up with 1 million files in your filesystem, which is not ideal). 

If you are doing a small-scale experiment with fewer than 100k equations, you can consider loading the entire dataset into memory before starting the experiment. On the other hand, if you are planning to do large-scale experiments, you may want to take a look at DeepLake or Webdatset. If we were to do this again, these are the tools I would use.
