### ISSUE TITLE
Unknown SymPy operator

### ISSUE THREAD

**Issue by alessandrosimon** [SymposiumOrganization/NeuralSymbolicRegressionThatScales#3]
Hi,
during training I sometimes get the warning:
`Unknown SymPy operator: zoo  ` (ComplexInfinity in SymPy)
Other unknown operators that came up are
`nan, oo,  asinh(c*sqrt(-x_1))`
The relevant method seems to be `Generator.sympy_to_prefix()` in `src.nesymres.dataset.generator`. The warning doesn't seem to interrupt the training but maybe it's better to handle those cases also.

**Comment by TommasoBendinelli** [comment]
This is handled correctly, we are printing it only for debugging/info. If there are too many of them you can disable the warning https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings

**Comment by alessandrosimon** [comment]
I see, that makes sense. I mistakenly thought that asinh() was part of the function dictionary.
