### ISSUE TITLE
dataload_format_to_csv script

### ISSUE THREAD

**Issue by bowenyou** [SymposiumOrganization/NeuralSymbolicRegressionThatScales#5]
When I run this script to try and convert my training sets to csv format, I intermittently run into the issue of out of memory (128GBs). Also, for some equations, the script appears to freeze (hours at a time before I have to cancel it). Is there something in the backend that is causing this? Could some generated equations "break" the script?

I've split the data into 1000 equations at a time and still run into this issue. Any help would be appreciated!

**Comment by TommasoBendinelli** [comment]
Hi Bowenyou,  We only tried to convert the validation sets (about 250) equations into a csv file, so the script is not really meant for converting huge amount of equations into csv format. I would try to print the currently processed equation and see which is the last one before freezing and keep an eye on the ram, (if usages grows linearly or it has a step)
