### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by mojivalipour** [SymposiumOrganization/NeuralSymbolicRegressionThatScales#6]
Do you have any plans to publish your datasets for reproducibility?

**Comment by lucabig** [comment]
Hi @mojivalipour , for practical reasons (very large dataset size >50GB), we do not have in our plans to release the dataset at the moment. The code in the repo should be sufficient to generate it though. For benchmarking we suggest looking at the equations of the test set, which are provided.

**Comment by mojivalipour** [comment]
If the storage is the issue, you can use this free service: https://degoo.com/ which offers 100 GB of free storage. Reproducibility depends heavily on this. We have tried your data generator, but we always encountered odd situations at the end. There are times when it is stuck for a long time, and the speed of data generation is quite limited, so trying to regenerate your datasets is not a solution for us. We will appreciate it if you upload your datasets to reproduce your experiments.

**Comment by druidowm** [comment]
I would also greatly appreciate if the dataset were made available. Thank you for your help!
